// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnections() {
  return window['go']['network']['NetworkService']['GetConnections']();
}

export function Shutdown() {
  return window['go']['network']['NetworkService']['Shutdown']();
}

export function StartMonitoring(arg1) {
  return window['go']['network']['NetworkService']['StartMonitoring'](arg1);
}

export function Startup(arg1) {
  return window['go']['network']['NetworkService']['Startup'](arg1);
}

export function StopMonitoring() {
  return window['go']['network']['NetworkService']['StopMonitoring']();
}
