// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {context} from '../models';

export function GetConnections():Promise<Array<network.ConnectionInfo>>;

export function Shutdown():Promise<void>;

export function StartMonitoring(arg1:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopMonitoring():Promise<void>;
