// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['terminal']['TerminalService']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['terminal']['TerminalService']['CreateSession'](arg1, arg2, arg3);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['terminal']['TerminalService']['ResizeSession'](arg1, arg2, arg3);
}

export function Shutdown() {
  return window['go']['terminal']['TerminalService']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['terminal']['TerminalService']['Startup'](arg1);
}

export function WriteToSession(arg1, arg2) {
  return window['go']['terminal']['TerminalService']['WriteToSession'](arg1, arg2);
}
