// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function WriteToSession(arg1:string,arg2:string):Promise<void>;
