// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStats() {
  return window['go']['sysmon']['SysMonService']['GetStats']();
}

export function Shutdown() {
  return window['go']['sysmon']['SysMonService']['Shutdown']();
}

export function StartMonitoring(arg1) {
  return window['go']['sysmon']['SysMonService']['StartMonitoring'](arg1);
}

export function Startup(arg1) {
  return window['go']['sysmon']['SysMonService']['Startup'](arg1);
}

export function StopMonitoring() {
  return window['go']['sysmon']['SysMonService']['StopMonitoring']();
}
