// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fileexplorer} from '../models';
import {context} from '../models';

export function GetDrives():Promise<Array<string>>;

export function GetHomeDir():Promise<string>;

export function GetPathSeparator():Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<fileexplorer.FileEntry>>;

export function OpenFile(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
