// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDrives() {
  return window['go']['fileexplorer']['FileExplorerService']['GetDrives']();
}

export function GetHomeDir() {
  return window['go']['fileexplorer']['FileExplorerService']['GetHomeDir']();
}

export function GetPathSeparator() {
  return window['go']['fileexplorer']['FileExplorerService']['GetPathSeparator']();
}

export function ListDirectory(arg1) {
  return window['go']['fileexplorer']['FileExplorerService']['ListDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['fileexplorer']['FileExplorerService']['OpenFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['fileexplorer']['FileExplorerService']['Startup'](arg1);
}
